# Generated by Django 6.0 on 2026-05-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('travel', '✈️ Travel'), ('date', '💕 Date Ideas'), ('adventure', '🏔️ Adventure'), ('food', '🍽️ Food'), ('learning', '📚 Learn Together'), ('milestone', '🎯 Milestone'), ('other', '✨ Other')], default='other', max_length=20)),
                ('added_by', models.CharField(choices=[('me', 'Me'), ('shaira', 'Shaira')], default='me', max_length=20)),
                ('status', models.CharField(choices=[('pending', '⏳ Not Yet'), ('planned', '📅 Planned'), ('completed', '✅ Completed')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, '⭐ Low'), (2, '⭐⭐ Medium'), (3, '⭐⭐⭐ High')], default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, choices=[('me', 'Me'), ('shaira', 'Shaira'), ('both', 'Both')], max_length=20, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bucketlist/')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_items', to='accounts.couple')),
            ],
            options={
                'ordering': ['status', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoveLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_letters', to='accounts.couple')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='year_covers/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='accounts.couple')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('couple', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SongRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('recommended_by', models.CharField(choices=[('me', 'Me'), ('shaira', 'Shaira')], max_length=20)),
                ('recommended_to', models.CharField(choices=[('me', 'Me'), ('shaira', 'Shaira')], max_length=20)),
                ('youtube_link', models.URLField(blank=True)),
                ('spotify_link', models.URLField(blank=True)),
                ('note', models.TextField(blank=True, help_text='Why you recommended this song...')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('mood', models.CharField(blank=True, choices=[('romantic', '💕 Romantic'), ('happy', '😊 Happy'), ('chill', '😌 Chill'), ('energetic', '⚡ Energetic'), ('nostalgic', '🥺 Nostalgic'), ('sad', '😢 Sad'), ('party', '🎉 Party')], max_length=50)),
                ('is_listened', models.BooleanField(default=False)),
                ('listened_date', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_recommendations', to='accounts.couple')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_recommendations', to='diary_project.year')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=500)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (1 point)'), ('medium', 'Medium (3 points)'), ('hard', 'Hard (5 points)')], default='easy', max_length=10)),
                ('category', models.CharField(choices=[('about_me', 'About Me'), ('about_shaira', 'About Shaira'), ('our_relationship', 'Our Relationship'), ('fun_facts', 'Fun Facts'), ('memories', 'Memories'), ('other', 'Other')], default='other', max_length=20)),
                ('created_by', models.CharField(choices=[('me', 'Me'), ('shaira', 'Shaira')], default='me', max_length=20)),
                ('hint', models.TextField(blank=True)),
                ('is_used', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='accounts.couple')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='diary_project.year')),
            ],
            options={
                'ordering': ['difficulty', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='memories/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('favorite_quote', models.TextField(blank=True)),
                ('memory_type', models.CharField(choices=[('milestone', '💫 Milestone'), ('date', '💕 Date'), ('travel', '✈️ Travel'), ('everyday', '🌸 Everyday Magic'), ('special', '✨ Special Moment')], default='special', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='accounts.couple')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='diary_project.year')),
            ],
            options={
                'verbose_name_plural': 'Memories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnimeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('my_ratings', models.JSONField(blank=True, default=dict)),
                ('shaira_ratings', models.JSONField(blank=True, default=dict)),
                ('my_overall', models.FloatField(default=0)),
                ('shaira_overall', models.FloatField(default=0)),
                ('combined_overall', models.FloatField(default=0)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('watched_together', models.BooleanField(default=True)),
                ('my_favorite_character', models.CharField(blank=True, max_length=100)),
                ('shaira_favorite_character', models.CharField(blank=True, max_length=100)),
                ('favorite_moment', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('watched_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_ratings', to='accounts.couple')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_ratings', to='diary_project.year')),
            ],
            options={
                'ordering': ['-combined_overall', 'title'],
            },
        ),
        migrations.CreateModel(
            name='YearFunFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_food', models.CharField(blank=True, max_length=100)),
                ('favorite_anime', models.CharField(blank=True, max_length=200)),
                ('song_of_the_year', models.CharField(blank=True, max_length=200)),
                ('best_moment', models.TextField(blank=True)),
                ('inside_jokes', models.TextField(blank=True)),
                ('places_visited', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_fun_facts', to='accounts.couple')),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fun_facts', to='diary_project.year')),
            ],
        ),
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_score', models.IntegerField(default=0)),
                ('shaira_score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_questions', models.ManyToManyField(blank=True, to='diary_project.quizquestion')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_scores', to='accounts.couple')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_scores', to='diary_project.year')),
            ],
            options={
                'unique_together': {('year',)},
            },
        ),
        migrations.CreateModel(
            name='CoupleGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=60)),
                ('my_score', models.IntegerField(default=0)),
                ('shaira_score', models.IntegerField(default=0)),
                ('game_history', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to='accounts.couple')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to='diary_project.year')),
            ],
            options={
                'unique_together': {('year', 'game_name')},
            },
        ),
        migrations.CreateModel(
            name='AnimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='Star', max_length=50)),
                ('color', models.CharField(default='from-blue-400 to-cyan-400', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_categories', to='accounts.couple')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_categories', to='diary_project.year')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('couple', 'year', 'name')},
            },
        ),
    ]
