# Generated by Django 6.0 on 2026-05-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animecategory',
            name='color',
            field=models.CharField(default='from-blue-400 to-cyan-400', max_length=50),
        ),
        migrations.AddField(
            model_name='animecategory',
            name='icon',
            field=models.CharField(default='Star', max_length=50),
        ),
        migrations.AlterField(
            model_name='bucketlistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bucketlist/'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memories/'),
        ),
        migrations.AlterField(
            model_name='songrecommendation',
            name='recommended_by',
            field=models.CharField(choices=[('me', 'Yuri'), ('shaira', 'Shaira')], max_length=20),
        ),
        migrations.AlterField(
            model_name='songrecommendation',
            name='recommended_to',
            field=models.CharField(choices=[('me', 'Yuri'), ('shaira', 'Shaira')], max_length=20),
        ),
        migrations.AlterField(
            model_name='year',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='year_covers/'),
        ),
    ]
