# Generated by Django 6.0 on 2026-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animecategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='songrecommendation',
            name='album',
        ),
        migrations.RemoveField(
            model_name='songrecommendation',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='songrecommendation',
            name='listened_date',
        ),
        migrations.RemoveField(
            model_name='songrecommendation',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='songrecommendation',
            name='note',
        ),
        migrations.AddField(
            model_name='animecategory',
            name='media_type',
            field=models.CharField(choices=[('anime', '🎬 Anime'), ('movie', '🎥 Movie'), ('show', '📺 TV Show')], default='anime', max_length=20),
        ),
        migrations.AddField(
            model_name='animerating',
            name='media_type',
            field=models.CharField(choices=[('anime', '🎬 Anime'), ('movie', '🎥 Movie'), ('show', '📺 TV Show')], default='anime', max_length=20),
        ),
        migrations.AlterField(
            model_name='songrecommendation',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='songrecommendation',
            name='recommended_by',
            field=models.CharField(choices=[('me', 'Yuri'), ('shaira', 'Shaira')], max_length=20),
        ),
        migrations.AlterField(
            model_name='songrecommendation',
            name='recommended_to',
            field=models.CharField(choices=[('me', 'Yuri'), ('shaira', 'Shaira')], max_length=20),
        ),
        migrations.AlterField(
            model_name='songrecommendation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='animecategory',
            unique_together={('year', 'name', 'media_type')},
        ),
    ]
