# Generated by Django 6.0 on 2026-05-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrecommendation',
            name='mood',
            field=models.CharField(choices=[('romantic', '💕 Romantic'), ('sad', '😢 Sad'), ('chill', '😌 Chill'), ('other', '✨ Other')], default='other', max_length=20),
        ),
    ]
