# Generated by Django 6.0 on 2026-05-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_project', '0002_songrecommendation_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year_number',
            field=models.IntegerField(),
        ),
    ]
