# Generated by Django 6.0 on 2026-05-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_project', '0002_alter_animecategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='memory_type',
            field=models.CharField(choices=[('milestone', '💫 Milestone'), ('date', '💕 Date'), ('travel', '✈️ Travel'), ('everyday', '🌸 Everyday Magic'), ('special', '✨ Special Moment'), ('sad', '💙 Sad Moment')], default='special', max_length=20),
        ),
    ]
