# Generated by Django 6.0 on 2026-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_project', '0002_animecategory_color_animecategory_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animecategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='animecategory',
            name='icon',
        ),
        migrations.AlterField(
            model_name='bucketlistitem',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='songrecommendation',
            name='recommended_by',
            field=models.CharField(choices=[('me', 'Me'), ('shaira', 'Shaira')], max_length=20),
        ),
        migrations.AlterField(
            model_name='songrecommendation',
            name='recommended_to',
            field=models.CharField(choices=[('me', 'Me'), ('shaira', 'Shaira')], max_length=20),
        ),
        migrations.AlterField(
            model_name='year',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
